services:
  - type: web
    name: resux-api
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: VOYAGE_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: openrouter
      - key: SUPABASE_PROJECT_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
